### ISSUE TITLE
SWC meta issue

### ISSUE THREAD

**Issue by stefanpenner** [stefanpenner/broccoli-swc#9]
Tracking issue for anything that may need to be fixed in SWC

- [x] ~https://github.com/swc-project/swc/issues/151 commonjs transformation not working via JS API #151~
- [x] ~https://github.com/swc-project/swc/issues/154 add support for "named amd" module targets~
- [ ] https://github.com/swc-project/swc/issues/104 Something like @babel/preset-env
- [x] ~https://github.com/swc-project/swc/issues/155 add support for external helpers~
- [ ] https://github.com/swc-project/swc/issues/18 Plugin system (we often rely on custom build steps such as debug/assert/feature flag stripping)
- [x] ~https://github.com/swc-project/swc/issues/248 correctly include externalized helpers in amd output~
- [x] https://github.com/swc-project/swc/issues/257 JS parse error
- [x] https://github.com/swc-project/swc/issues/260 JS parse error
- [x] https://github.com/swc-project/swc/issues/261 JS unicode parse error
- [x] https://github.com/swc-project/swc/issues/262 disable _interopRequireDefault

**Comment by kdy1** [comment]
Fixed swc-project/swc#257, swc-project/swc#260, swc-project/swc#261, swc-project/swc#262

**Comment by stefanpenner** [comment]
@kdy1 you rock!

**Comment by kdy1** [comment]
I have to send my mac in to get the keyboard fixed. Sorry for delay.
